/*
 * Główne okno
 */
package classes;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import tablemodels.*;

/**
 *
 * @author Dominik
 */
public class GUI extends javax.swing.JFrame {

    Function f;
    Employee user;
    List<Product> ordered_list;
    Double price= 0.0;
    private static final int CAT_GPU = 1;
    private static final int CAT_HDD = 2;
    private static final int CAT_RAM = 3;
    private static final int CAT_KEYBOARD = 5;
    private static final int CAT_POWER_SUPPLY = 6;
    private static final int CAT_COOLING = 7;
    private static final int CAT_CPU = 8;
    private static final int CAT_MB = 9;
    private static final int CAT_MONITOR = 10;
    private static final int CAT_MOUSE = 11;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        f = new Function();
        //ukrycie wszystkich paneli
        jPanelMailbox.setVisible(false);
        jButtonShowEmail.setVisible(false);
        jPanelWriteMail.setVisible(false);
        jPanelLogin.setVisible(false);//odznaczyć przy logowaniu ręcznym
        jPanelRepairForm.setVisible(false);
        jPanelRepairsTable.setVisible(false);
        //jButtonRepairDesc.setVisible(false);
        //jButtonRepairCheck.setVisible(false);
        jPanelWarehouse.setVisible(false);
        jPanelFood.setVisible(false);
        jPanelPartsOrders.setVisible(false);
        
        
        
        
        f.fillComboboxWithEmployees(jComboBoxLoginEmployees);
        user = new Employee(1,"Andrzej","Kowalski","a.kowal@wp.pl","OBXY2JIQxC2AJ/xO7bRukw==","Admin");
        //to usunąć żeby logowanie miało sens
        if(f.thereIsNewMail(user)){
            jMenuEmails.setForeground(Color.red);
            //JOptionPane.showMessageDialog(null, "Jest mail");
        }
        else{
            jMenuEmails.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPartsCategories = new javax.swing.ButtonGroup();
        jPanelSideButtons = new javax.swing.JPanel();
        jButtonShowEmail = new javax.swing.JButton();
        jButtonRepair = new javax.swing.JButton();
        jButtonShowRepairs = new javax.swing.JButton();
        jButtonFoodOrders = new javax.swing.JButton();
        jButtonShowWarehouse = new javax.swing.JButton();
        jButtonPartsOrders = new javax.swing.JButton();
        jPanelMailbox = new javax.swing.JPanel();
        jScrollPaneForMailbox = new javax.swing.JScrollPane();
        jTableMailbox = new javax.swing.JTable();
        jPanelWriteMail = new javax.swing.JPanel();
        jComboBoxEmployeeList = new javax.swing.JComboBox();
        jScrollPaneWriteMail = new javax.swing.JScrollPane();
        jTextAreaWriteMail = new javax.swing.JTextArea();
        jButtonMailSend = new javax.swing.JButton();
        jPanelLogin = new javax.swing.JPanel();
        jComboBoxLoginEmployees = new javax.swing.JComboBox();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jPanelRepairForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldClientsName = new javax.swing.JTextField();
        jTextFieldClientsFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRepairInfo = new javax.swing.JTextArea();
        jButtonRepairSend = new javax.swing.JButton();
        jPanelRepairsTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRepairs = new javax.swing.JTable();
        jButtonRepairDesc = new javax.swing.JButton();
        jButtonRepairCheck = new javax.swing.JButton();
        jButtonRepairTableBack = new javax.swing.JButton();
        jPanelWarehouse = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableWarehouse = new javax.swing.JTable();
        jTextFieldBrowser = new javax.swing.JTextField();
        jButtonBrowser = new javax.swing.JButton();
        jPanelFood = new javax.swing.JPanel();
        jScrollPaneFoodToOrder = new javax.swing.JScrollPane();
        jTableFoodToOrder = new javax.swing.JTable();
        jScrollPaneFoodOrdered = new javax.swing.JScrollPane();
        jTableFoodOrdered = new javax.swing.JTable();
        jButtonAddFoodProduct = new javax.swing.JButton();
        jTextFieldFoodQuantity = new javax.swing.JTextField();
        jButtonOrderFood = new javax.swing.JButton();
        jButtonFoodQuantityDelete = new javax.swing.JButton();
        jPanelPartsOrders = new javax.swing.JPanel();
        jRadioButtonGPU_1 = new javax.swing.JRadioButton();
        jRadioHDD_2 = new javax.swing.JRadioButton();
        jLabelCategories = new javax.swing.JLabel();
        jRadioButtonRAM_3 = new javax.swing.JRadioButton();
        jRadioButtonKeyboard_5 = new javax.swing.JRadioButton();
        jRadioButtonPowerSupply_6 = new javax.swing.JRadioButton();
        jRadioButtonCooling_7 = new javax.swing.JRadioButton();
        jRadioButtonCPU_8 = new javax.swing.JRadioButton();
        jRadioButtonMB_9 = new javax.swing.JRadioButton();
        jRadioButtonMonitor_10 = new javax.swing.JRadioButton();
        jRadioButtonMouse_11 = new javax.swing.JRadioButton();
        jComboBoxPartsOrders = new javax.swing.JComboBox();
        jScrollPanePartsOrders = new javax.swing.JScrollPane();
        jTablePartsOrders = new javax.swing.JTable();
        jButtonAddPartToOrder = new javax.swing.JButton();
        jTextFieldPartQuantity = new javax.swing.JTextField();
        jButtonPartOrder = new javax.swing.JButton();
        jTextFieldPartsPrice = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuEmails = new javax.swing.JMenu();
        jMenuItemWriteEmail = new javax.swing.JMenuItem();
        jMenuItemMailbox = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelSideButtons.setBackground(new java.awt.Color(204, 255, 255));

        jButtonShowEmail.setText("Wyświetl ");
        jButtonShowEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowEmailActionPerformed(evt);
            }
        });

        jButtonRepair.setText("Naprawa");
        jButtonRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepairActionPerformed(evt);
            }
        });

        jButtonShowRepairs.setText("Zamówienia do naprawy");
        jButtonShowRepairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowRepairsActionPerformed(evt);
            }
        });

        jButtonFoodOrders.setText("Zamawianie jedzenia");
        jButtonFoodOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodOrdersActionPerformed(evt);
            }
        });

        jButtonShowWarehouse.setText("Stan magazynowy");
        jButtonShowWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowWarehouseActionPerformed(evt);
            }
        });

        jButtonPartsOrders.setText("Zamawianie części");
        jButtonPartsOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPartsOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSideButtonsLayout = new javax.swing.GroupLayout(jPanelSideButtons);
        jPanelSideButtons.setLayout(jPanelSideButtonsLayout);
        jPanelSideButtonsLayout.setHorizontalGroup(
            jPanelSideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonShowEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRepair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonShowRepairs)
                    .addComponent(jButtonFoodOrders)
                    .addComponent(jButtonShowWarehouse)
                    .addComponent(jButtonPartsOrders))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSideButtonsLayout.setVerticalGroup(
            jPanelSideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonShowEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRepair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonShowRepairs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFoodOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonShowWarehouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPartsOrders)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableMailbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneForMailbox.setViewportView(jTableMailbox);

        javax.swing.GroupLayout jPanelMailboxLayout = new javax.swing.GroupLayout(jPanelMailbox);
        jPanelMailbox.setLayout(jPanelMailboxLayout);
        jPanelMailboxLayout.setHorizontalGroup(
            jPanelMailboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneForMailbox, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        jPanelMailboxLayout.setVerticalGroup(
            jPanelMailboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneForMailbox, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        jPanelWriteMail.setPreferredSize(new java.awt.Dimension(659, 579));

        jComboBoxEmployeeList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmployeeListActionPerformed(evt);
            }
        });

        jTextAreaWriteMail.setColumns(20);
        jTextAreaWriteMail.setRows(5);
        jScrollPaneWriteMail.setViewportView(jTextAreaWriteMail);

        jButtonMailSend.setText("Wyślij");
        jButtonMailSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMailSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelWriteMailLayout = new javax.swing.GroupLayout(jPanelWriteMail);
        jPanelWriteMail.setLayout(jPanelWriteMailLayout);
        jPanelWriteMailLayout.setHorizontalGroup(
            jPanelWriteMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWriteMailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWriteMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEmployeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMailSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneWriteMail, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWriteMailLayout.setVerticalGroup(
            jPanelWriteMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWriteMailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWriteMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneWriteMail, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addGroup(jPanelWriteMailLayout.createSequentialGroup()
                        .addComponent(jComboBoxEmployeeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMailSend)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jComboBoxLoginEmployees.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonLogin.setText("Zaloguj");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldPassword)
                            .addComponent(jComboBoxLoginEmployees, 0, 210, Short.MAX_VALUE)))
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButtonLogin)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jComboBoxLoginEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogin)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        jLabel1.setText("Imie klienta: ");

        jLabel2.setText("Nazwisko klienta: ");

        jTextFieldClientsName.setText("jTextField1");

        jTextFieldClientsFullName.setText("jTextField1");

        jLabel3.setText("Opis (opcjonalnie):");

        jTextAreaRepairInfo.setColumns(20);
        jTextAreaRepairInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRepairInfo);

        jButtonRepairSend.setText("Wyślij informację");
        jButtonRepairSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepairSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRepairFormLayout = new javax.swing.GroupLayout(jPanelRepairForm);
        jPanelRepairForm.setLayout(jPanelRepairFormLayout);
        jPanelRepairFormLayout.setHorizontalGroup(
            jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepairFormLayout.createSequentialGroup()
                .addGroup(jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRepairFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldClientsName, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(jTextFieldClientsFullName))))
                    .addGroup(jPanelRepairFormLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButtonRepairSend)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanelRepairFormLayout.setVerticalGroup(
            jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepairFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldClientsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldClientsFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRepairFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonRepairSend)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jTableRepairs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableRepairs);

        jButtonRepairDesc.setText("Pokaż opis");
        jButtonRepairDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepairDescActionPerformed(evt);
            }
        });

        jButtonRepairCheck.setText("Zatwierdź naprawę");
        jButtonRepairCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepairCheckActionPerformed(evt);
            }
        });

        jButtonRepairTableBack.setText("Powrót");
        jButtonRepairTableBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepairTableBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRepairsTableLayout = new javax.swing.GroupLayout(jPanelRepairsTable);
        jPanelRepairsTable.setLayout(jPanelRepairsTableLayout);
        jPanelRepairsTableLayout.setHorizontalGroup(
            jPanelRepairsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepairsTableLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jButtonRepairDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRepairCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRepairTableBack)
                .addGap(0, 142, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelRepairsTableLayout.setVerticalGroup(
            jPanelRepairsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRepairsTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRepairsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRepairDesc)
                    .addGroup(jPanelRepairsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonRepairCheck)
                        .addComponent(jButtonRepairTableBack)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTableWarehouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableWarehouse);

        jTextFieldBrowser.setText("jTextField1");

        jButtonBrowser.setText("Wyszukaj");
        jButtonBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelWarehouseLayout = new javax.swing.GroupLayout(jPanelWarehouse);
        jPanelWarehouse.setLayout(jPanelWarehouseLayout);
        jPanelWarehouseLayout.setHorizontalGroup(
            jPanelWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(jPanelWarehouseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWarehouseLayout.setVerticalGroup(
            jPanelWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWarehouseLayout.createSequentialGroup()
                .addGroup(jPanelWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTableFoodToOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneFoodToOrder.setViewportView(jTableFoodToOrder);

        jTableFoodOrdered.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneFoodOrdered.setViewportView(jTableFoodOrdered);

        jButtonAddFoodProduct.setText("Dodaj");
        jButtonAddFoodProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFoodProductActionPerformed(evt);
            }
        });

        jTextFieldFoodQuantity.setText("jTextField1");

        jButtonOrderFood.setText("Zamów");
        jButtonOrderFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderFoodActionPerformed(evt);
            }
        });

        jButtonFoodQuantityDelete.setText("Odejmij");
        jButtonFoodQuantityDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodQuantityDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFoodLayout = new javax.swing.GroupLayout(jPanelFood);
        jPanelFood.setLayout(jPanelFoodLayout);
        jPanelFoodLayout.setHorizontalGroup(
            jPanelFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFoodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFoodLayout.createSequentialGroup()
                        .addComponent(jScrollPaneFoodOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jScrollPaneFoodToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFoodLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFoodQuantityDelete)
                        .addGap(60, 60, 60)
                        .addGroup(jPanelFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFoodQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFoodLayout.createSequentialGroup()
                                .addComponent(jButtonOrderFood)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonAddFoodProduct)))
                        .addGap(152, 152, 152))))
        );
        jPanelFoodLayout.setVerticalGroup(
            jPanelFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFoodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneFoodToOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(jScrollPaneFoodOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jTextFieldFoodQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFoodQuantityDelete)
                    .addComponent(jButtonOrderFood)
                    .addComponent(jButtonAddFoodProduct))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        buttonGroupPartsCategories.add(jRadioButtonGPU_1);
        jRadioButtonGPU_1.setText("Karty graficzne");
        jRadioButtonGPU_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGPU_1ActionPerformed(evt);
            }
        });

        buttonGroupPartsCategories.add(jRadioHDD_2);
        jRadioHDD_2.setText("Dyski twarde");
        jRadioHDD_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioHDD_2ActionPerformed(evt);
            }
        });

        jLabelCategories.setText("Kategorie");

        buttonGroupPartsCategories.add(jRadioButtonRAM_3);
        jRadioButtonRAM_3.setText("Pamięć RAM");
        jRadioButtonRAM_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRAM_3ActionPerformed(evt);
            }
        });

        buttonGroupPartsCategories.add(jRadioButtonKeyboard_5);
        jRadioButtonKeyboard_5.setText("Klawiatury");
        jRadioButtonKeyboard_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKeyboard_5ActionPerformed(evt);
            }
        });

        buttonGroupPartsCategories.add(jRadioButtonPowerSupply_6);
        jRadioButtonPowerSupply_6.setText("Zasilacze");
        jRadioButtonPowerSupply_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPowerSupply_6ActionPerformed(evt);
            }
        });

        buttonGroupPartsCategories.add(jRadioButtonCooling_7);
        jRadioButtonCooling_7.setText("Chłodzenie");
        jRadioButtonCooling_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCooling_7ActionPerformed(evt);
            }
        });

        buttonGroupPartsCategories.add(jRadioButtonCPU_8);
        jRadioButtonCPU_8.setText("Procesory");
        jRadioButtonCPU_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCPU_8ActionPerformed(evt);
            }
        });

        buttonGroupPartsCategories.add(jRadioButtonMB_9);
        jRadioButtonMB_9.setText("Płyty główne");
        jRadioButtonMB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMB_9ActionPerformed(evt);
            }
        });

        buttonGroupPartsCategories.add(jRadioButtonMonitor_10);
        jRadioButtonMonitor_10.setText("Monitory");
        jRadioButtonMonitor_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMonitor_10ActionPerformed(evt);
            }
        });

        buttonGroupPartsCategories.add(jRadioButtonMouse_11);
        jRadioButtonMouse_11.setText("Myszki");
        jRadioButtonMouse_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMouse_11ActionPerformed(evt);
            }
        });

        jComboBoxPartsOrders.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTablePartsOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePartsOrders.setViewportView(jTablePartsOrders);

        jButtonAddPartToOrder.setText("Dodaj");
        jButtonAddPartToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPartToOrderActionPerformed(evt);
            }
        });

        jTextFieldPartQuantity.setText("jTextField1");

        jButtonPartOrder.setText("Zamów");
        jButtonPartOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPartOrderActionPerformed(evt);
            }
        });

        jTextFieldPartsPrice.setText("jTextField1");

        javax.swing.GroupLayout jPanelPartsOrdersLayout = new javax.swing.GroupLayout(jPanelPartsOrders);
        jPanelPartsOrders.setLayout(jPanelPartsOrdersLayout);
        jPanelPartsOrdersLayout.setHorizontalGroup(
            jPanelPartsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPartsOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPartsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPartsOrdersLayout.createSequentialGroup()
                        .addGroup(jPanelPartsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPartsOrdersLayout.createSequentialGroup()
                                .addComponent(jButtonAddPartToOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPartQuantity))
                            .addComponent(jComboBoxPartsOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonMouse_11)
                            .addComponent(jRadioButtonMonitor_10)
                            .addComponent(jRadioButtonMB_9)
                            .addComponent(jRadioButtonCPU_8)
                            .addComponent(jRadioButtonCooling_7)
                            .addComponent(jRadioButtonPowerSupply_6)
                            .addComponent(jRadioButtonKeyboard_5)
                            .addComponent(jRadioButtonRAM_3)
                            .addComponent(jLabelCategories)
                            .addComponent(jRadioButtonGPU_1)
                            .addComponent(jRadioHDD_2))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPanePartsOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                    .addGroup(jPanelPartsOrdersLayout.createSequentialGroup()
                        .addGroup(jPanelPartsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPartOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPartsPrice))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPartsOrdersLayout.setVerticalGroup(
            jPanelPartsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPartsOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPartsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPanePartsOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addGroup(jPanelPartsOrdersLayout.createSequentialGroup()
                        .addComponent(jLabelCategories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonGPU_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioHDD_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonRAM_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonKeyboard_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPowerSupply_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCooling_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCPU_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMB_9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMonitor_10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMouse_11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPartsOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPartsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddPartToOrder)
                    .addComponent(jTextFieldPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPartOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPartsPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jMenuEmails.setText("Wiadomości");

        jMenuItemWriteEmail.setText("Napisz");
        jMenuItemWriteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWriteEmailActionPerformed(evt);
            }
        });
        jMenuEmails.add(jMenuItemWriteEmail);

        jMenuItemMailbox.setText("Skrzynka Odbiorcza");
        jMenuItemMailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMailboxActionPerformed(evt);
            }
        });
        jMenuEmails.add(jMenuItemMailbox);

        jMenuBar.add(jMenuEmails);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSideButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMailbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 141, Short.MAX_VALUE)
                    .addComponent(jPanelWriteMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 141, Short.MAX_VALUE)
                    .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 141, Short.MAX_VALUE)
                    .addComponent(jPanelRepairForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 193, Short.MAX_VALUE)
                    .addComponent(jPanelRepairsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 200, Short.MAX_VALUE)
                    .addComponent(jPanelWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 187, Short.MAX_VALUE)
                    .addComponent(jPanelFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 159, Short.MAX_VALUE)
                    .addComponent(jPanelPartsOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSideButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMailbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelWriteMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRepairForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelRepairsTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelWarehouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelFood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPartsOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMailboxActionPerformed
        //Otwieranie skrzynki z wiadomościami
        jPanelMailbox.setVisible(true);
        if(jPanelWriteMail.isVisible()) 
            jPanelWriteMail.setVisible(false);
        jButtonShowEmail.setVisible(true);
        
        f.fillTableWithEmailsForUser(jTableMailbox,user);
    }//GEN-LAST:event_jMenuItemMailboxActionPerformed

    private void jButtonShowEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowEmailActionPerformed
        //Wyświetlanie meila
        Email email = new Email();
        int row = jTableMailbox.getSelectedRow();
        if (row < 0) {
                    JOptionPane.showMessageDialog(null,"Wybierz Email");				
                    return;
		}
        
        email = (Email) jTableMailbox.getValueAt(row, EmailTableModel.OBJECT_COL);
        
        JOptionPane.showMessageDialog(null, email.getText());//tu jakoś poprawić
        f.setEmailChecked(email);
        f.fillTableWithEmailsForUser(jTableMailbox,user);
        if(f.thereIsNewMail(user)){
            jMenuEmails.setForeground(Color.red);
            //JOptionPane.showMessageDialog(null, "Jest mail");
        }
        else{
            jMenuEmails.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jButtonShowEmailActionPerformed

    private void jMenuItemWriteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWriteEmailActionPerformed
        // Pisanie meila
        jPanelWriteMail.setVisible(true);
        if(jPanelMailbox.isVisible()) 
            jPanelMailbox.setVisible(false);
        
        f.fillComboboxWithEmployeesWithoutUser(jComboBoxEmployeeList,user);
        
    }//GEN-LAST:event_jMenuItemWriteEmailActionPerformed

    private void jButtonMailSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMailSendActionPerformed
        Employee employee = (Employee) jComboBoxEmployeeList.getSelectedItem();
        int id_sender = user.getId();
        int id_receiver = employee.getId();
        String text = jTextAreaWriteMail.getText();
        
        Email email = new Email(id_sender, id_receiver, text,false);
        f.addEmail(email);
        
        JOptionPane.showMessageDialog(null, "Wysłano");
    }//GEN-LAST:event_jButtonMailSendActionPerformed

    private void jComboBoxEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmployeeListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEmployeeListActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // Logowanie 
        try{
        Employee e = (Employee) jComboBoxLoginEmployees.getSelectedItem();
        String password = jPasswordFieldPassword.getText();
        String encryptedpassword = f.encrypt(password);
        if(!encryptedpassword.equals(e.getPassword()))
            throw new Exception();
        
        user = e;
        jPanelLogin.setVisible(false);
        this.setTitle("Witaj " + user.getName() + ' ' + user.getFull_name());
        
        if(f.thereIsNewMail(user)){
            jMenuEmails.setBackground(Color.red);
        }
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Złe hasło");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepairActionPerformed
        // Przyjmowanie do naprawy
        jPanelRepairForm.setVisible(true);
        jTextFieldClientsName.setText("");
        jTextFieldClientsFullName.setText("");
        
    }//GEN-LAST:event_jButtonRepairActionPerformed

    private void jButtonRepairSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepairSendActionPerformed
        // Wysyłanie formularza do naprawy
        try{
            String client_name = jTextFieldClientsName.getText();
            String client_full_name = jTextFieldClientsFullName.getText();
            String desc = jTextAreaRepairInfo.getText();
            
            Repair temp = new Repair(user.getId(),client_name,client_full_name,desc,false);
            f.addRepair(temp);
            JOptionPane.showMessageDialog(null, "Dodano");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error adding Repair Form");
        }
    }//GEN-LAST:event_jButtonRepairSendActionPerformed

    private void jButtonShowRepairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowRepairsActionPerformed
        // Tabela z naprawami dla technika
        
        jPanelRepairsTable.setVisible(true);
        f.fillTableWithRepairs(jTableRepairs);
        
        //jButtonRepairDesc.setVisible(true);
        //jButtonRepairCheck.setVisible(true);
        
    }//GEN-LAST:event_jButtonShowRepairsActionPerformed

    private void jButtonRepairDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepairDescActionPerformed
        // Wyświetlanie opisu repaira
        
        Repair temp = new Repair();
        int row = jTableRepairs.getSelectedRow();
        if (row < 0) {
                    JOptionPane.showMessageDialog(null,"Wybierz Wpis");				
                    return;
		}
        
        temp = (Repair) jTableRepairs.getValueAt(row, RepairTableModel.OBJECT_COL);
        
        JOptionPane.showMessageDialog(null, temp.getDescription());//tu jakoś poprawić
    }//GEN-LAST:event_jButtonRepairDescActionPerformed

    private void jButtonRepairCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepairCheckActionPerformed
        // Zatwierdzanie wykonania naprawy
        
        Repair temp = new Repair();
        int row = jTableRepairs.getSelectedRow();
        if (row < 0) {
                    JOptionPane.showMessageDialog(null,"Wybierz Wpis");				
                    return;
		}
        
        temp = (Repair) jTableRepairs.getValueAt(row, RepairTableModel.OBJECT_COL);
        
        if(temp.isExecuted()){
            JOptionPane.showMessageDialog(null, "Już wykonano");
            return;
        }
        f.setRepairExecuted(temp);
        f.fillTableWithRepairs(jTableRepairs);
        
        
        
    }//GEN-LAST:event_jButtonRepairCheckActionPerformed

    private void jButtonRepairTableBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepairTableBackActionPerformed
        // Powrót z repairów
        
        jPanelRepairsTable.setVisible(false);
    }//GEN-LAST:event_jButtonRepairTableBackActionPerformed

    private void jButtonShowWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowWarehouseActionPerformed
        // Stan magazynowy
        
        jPanelWarehouse.setVisible(true);
        jTextFieldBrowser.setText("");
        f.fillTableWithPartsProducts(jTableWarehouse);
    }//GEN-LAST:event_jButtonShowWarehouseActionPerformed

    private void jButtonBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowserActionPerformed
        // wyszuiwanie zwykłe
        String name = jTextFieldBrowser.getText();
        f.fillTableWithPartsProducts(jTableWarehouse, name);
    }//GEN-LAST:event_jButtonBrowserActionPerformed

    private void jButtonFoodOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodOrdersActionPerformed
        // ZAmawianie jedzenia
        jPanelFood.setVisible(true);
        jTextFieldFoodQuantity.setText("");
        
        //wypełnienie tabel
        ordered_list = new ArrayList<>();
        List<Product> to_order_list = new ArrayList<>();
        to_order_list = f.getFoodProducts();
        
        ProductTableModel ordered_model = new ProductTableModel(ordered_list);
        ProductTableModel to_order_model = new ProductTableModel(to_order_list);
        
        jTableFoodOrdered.setModel(ordered_model);
        jTableFoodToOrder.setModel(to_order_model);
        
        f.selectColumns(jTableFoodOrdered,jTableFoodToOrder);
        
        
        
    }//GEN-LAST:event_jButtonFoodOrdersActionPerformed

    private void jButtonAddFoodProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFoodProductActionPerformed
        // przesuwanie produktów food między tabelami
        try{
        Product temp = new Product();
        int row = jTableFoodToOrder.getSelectedRow();
        if (row < 0) {
                    JOptionPane.showMessageDialog(null,"Wybierz Produkt");				
                    return;
		}
        
        temp = (Product) jTableFoodToOrder.getValueAt(row, ProductTableModel.OBJECT_COL);
        
        
        if(jTextFieldFoodQuantity.getText().equals("")) throw  new Exception();
        
        int quantity = Integer.parseInt(jTextFieldFoodQuantity.getText());
        temp.setQuantity(quantity); //pobranie ilości
       
        if(f.containsProductID(ordered_list, temp.getId())){// tu poprawić bo sie dublowało
            //JOptionPane.showMessageDialog(null,ordered_list);
            int old_value = ordered_list.get(ordered_list.indexOf(temp)).getQuantity();
            //JOptionPane.showMessageDialog(null, old_value);
            ordered_list.get(ordered_list.indexOf(temp)).addQuantity(old_value);
           // JOptionPane.showMessageDialog(null,temp);
        }
        else{
            ordered_list.add(temp);
        }
        f.refreshOrderedFood(jTableFoodOrdered,ordered_list);

        
        }
        catch(Exception e){
            
        }
        finally{
            jTextFieldFoodQuantity.setText(""); 
        }
    }//GEN-LAST:event_jButtonAddFoodProductActionPerformed

    private void jButtonOrderFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderFoodActionPerformed
        // Dodawanie zamówienia do bazy
        
        Order food_order = new Order(user.getId(),ordered_list);
        //JOptionPane.showMessageDialog(rootPane, food_order);
        f.addOrder(food_order);
        JOptionPane.showMessageDialog(null, "Zamówiono");
        ordered_list.clear();
        jPanelFood.setVisible(false);
    }//GEN-LAST:event_jButtonOrderFoodActionPerformed

    private void jButtonFoodQuantityDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodQuantityDeleteActionPerformed
        // Odejmowanie ilości produktów
        
        try{
        Product temp = new Product();
        int row = jTableFoodOrdered.getSelectedRow();
        if (row < 0) {
                    JOptionPane.showMessageDialog(null,"Wybierz Produkt");				
                    return;
		}
        
        temp = (Product) jTableFoodOrdered.getValueAt(row, ProductTableModel.OBJECT_COL);
        int quantity = Integer.parseInt(jTextFieldFoodQuantity.getText());
            
        if(quantity > ordered_list.get(ordered_list.indexOf(temp)).getQuantity()){
            //JOptionPane.showMessageDialog(null,ordered_list.get(ordered_list.indexOf(temp)).getQuantity());
            throw  new Exception();
        }
        else if(quantity == ordered_list.get(ordered_list.indexOf(temp)).getQuantity())
            ordered_list.remove(temp);
        else
        ordered_list.get(ordered_list.indexOf(temp)).substractQuantity(quantity);
            
 
            
        f.refreshOrderedFood(jTableFoodOrdered, ordered_list);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Niepoprawna ilość");
        }
        finally{
            jTextFieldFoodQuantity.setText("");       
        }
    }//GEN-LAST:event_jButtonFoodQuantityDeleteActionPerformed

    private void jButtonPartsOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPartsOrdersActionPerformed
        // Zamawianie części z hurtowni
        jPanelPartsOrders.setVisible(true);
        jComboBoxPartsOrders.removeAllItems();
        jTextFieldPartQuantity.setText("");
        jTextFieldPartsPrice.setText("");
        ordered_list = new ArrayList<>();
        f.refreshProductTable(jTablePartsOrders, ordered_list);
        price = 0.0;
    }//GEN-LAST:event_jButtonPartsOrdersActionPerformed

    private void jRadioButtonGPU_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGPU_1ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_GPU);
    }//GEN-LAST:event_jRadioButtonGPU_1ActionPerformed

    private void jRadioHDD_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioHDD_2ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_HDD);
    }//GEN-LAST:event_jRadioHDD_2ActionPerformed

    private void jRadioButtonRAM_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRAM_3ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_RAM);
    }//GEN-LAST:event_jRadioButtonRAM_3ActionPerformed

    private void jRadioButtonKeyboard_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKeyboard_5ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_KEYBOARD);
    }//GEN-LAST:event_jRadioButtonKeyboard_5ActionPerformed

    private void jRadioButtonPowerSupply_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPowerSupply_6ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_POWER_SUPPLY);
    }//GEN-LAST:event_jRadioButtonPowerSupply_6ActionPerformed

    private void jRadioButtonCooling_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCooling_7ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_COOLING);
    }//GEN-LAST:event_jRadioButtonCooling_7ActionPerformed

    private void jRadioButtonCPU_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCPU_8ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_CPU);
    }//GEN-LAST:event_jRadioButtonCPU_8ActionPerformed

    private void jRadioButtonMB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMB_9ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_MB);
    }//GEN-LAST:event_jRadioButtonMB_9ActionPerformed

    private void jRadioButtonMonitor_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMonitor_10ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders, CAT_MONITOR);
    }//GEN-LAST:event_jRadioButtonMonitor_10ActionPerformed

    private void jRadioButtonMouse_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMouse_11ActionPerformed
        f.fillComboboxWithPartsCat(jComboBoxPartsOrders,  CAT_MOUSE);
    }//GEN-LAST:event_jRadioButtonMouse_11ActionPerformed

    private void jButtonAddPartToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPartToOrderActionPerformed
        // Dodawanie produktów do tabeli
        try{
        
        Product temp = new Product();
        
        temp = (Product) jComboBoxPartsOrders.getSelectedItem();
        int quantity = Integer.parseInt(jTextFieldPartQuantity.getText());
        temp.setQuantity(quantity);
        price += temp.getRetail_price() * (1 + temp.getVat()) * quantity;
        ordered_list.add(temp);
        
        f.refreshProductTable(jTablePartsOrders, ordered_list);
        jTextFieldPartsPrice.setText(Double.toString(price));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonAddPartToOrderActionPerformed

    private void jButtonPartOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPartOrderActionPerformed
        // Wysłąnie zamówienia na części
        Order temp = new Order(user.getId(), ordered_list);
        f.addOrder(temp);
        JOptionPane.showMessageDialog(null, "Zrobione");
        jPanelPartsOrders.setVisible(false);
        price = 0.0;
        
        ordered_list.clear();
    }//GEN-LAST:event_jButtonPartOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                Function f = new Function();
                
                /*
                 List<Order> list = new ArrayList<Order>();
                 list = f.getAllOrders();
                 JOptionPane.showMessageDialog(null, list);
                 */

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPartsCategories;
    private javax.swing.JButton jButtonAddFoodProduct;
    private javax.swing.JButton jButtonAddPartToOrder;
    private javax.swing.JButton jButtonBrowser;
    private javax.swing.JButton jButtonFoodOrders;
    private javax.swing.JButton jButtonFoodQuantityDelete;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonMailSend;
    private javax.swing.JButton jButtonOrderFood;
    private javax.swing.JButton jButtonPartOrder;
    private javax.swing.JButton jButtonPartsOrders;
    private javax.swing.JButton jButtonRepair;
    private javax.swing.JButton jButtonRepairCheck;
    private javax.swing.JButton jButtonRepairDesc;
    private javax.swing.JButton jButtonRepairSend;
    private javax.swing.JButton jButtonRepairTableBack;
    private javax.swing.JButton jButtonShowEmail;
    private javax.swing.JButton jButtonShowRepairs;
    private javax.swing.JButton jButtonShowWarehouse;
    private javax.swing.JComboBox jComboBoxEmployeeList;
    private javax.swing.JComboBox jComboBoxLoginEmployees;
    private javax.swing.JComboBox jComboBoxPartsOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCategories;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEmails;
    private javax.swing.JMenuItem jMenuItemMailbox;
    private javax.swing.JMenuItem jMenuItemWriteEmail;
    private javax.swing.JPanel jPanelFood;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelMailbox;
    private javax.swing.JPanel jPanelPartsOrders;
    private javax.swing.JPanel jPanelRepairForm;
    private javax.swing.JPanel jPanelRepairsTable;
    private javax.swing.JPanel jPanelSideButtons;
    private javax.swing.JPanel jPanelWarehouse;
    private javax.swing.JPanel jPanelWriteMail;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JRadioButton jRadioButtonCPU_8;
    private javax.swing.JRadioButton jRadioButtonCooling_7;
    private javax.swing.JRadioButton jRadioButtonGPU_1;
    private javax.swing.JRadioButton jRadioButtonKeyboard_5;
    private javax.swing.JRadioButton jRadioButtonMB_9;
    private javax.swing.JRadioButton jRadioButtonMonitor_10;
    private javax.swing.JRadioButton jRadioButtonMouse_11;
    private javax.swing.JRadioButton jRadioButtonPowerSupply_6;
    private javax.swing.JRadioButton jRadioButtonRAM_3;
    private javax.swing.JRadioButton jRadioHDD_2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneFoodOrdered;
    private javax.swing.JScrollPane jScrollPaneFoodToOrder;
    private javax.swing.JScrollPane jScrollPaneForMailbox;
    private javax.swing.JScrollPane jScrollPanePartsOrders;
    private javax.swing.JScrollPane jScrollPaneWriteMail;
    private javax.swing.JTable jTableFoodOrdered;
    private javax.swing.JTable jTableFoodToOrder;
    private javax.swing.JTable jTableMailbox;
    private javax.swing.JTable jTablePartsOrders;
    private javax.swing.JTable jTableRepairs;
    private javax.swing.JTable jTableWarehouse;
    private javax.swing.JTextArea jTextAreaRepairInfo;
    private javax.swing.JTextArea jTextAreaWriteMail;
    private javax.swing.JTextField jTextFieldBrowser;
    private javax.swing.JTextField jTextFieldClientsFullName;
    private javax.swing.JTextField jTextFieldClientsName;
    private javax.swing.JTextField jTextFieldFoodQuantity;
    private javax.swing.JTextField jTextFieldPartQuantity;
    private javax.swing.JTextField jTextFieldPartsPrice;
    // End of variables declaration//GEN-END:variables
}
